name: CI/CD with Docker

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main
  pull_request:
    branches:
      - main  # Проверять PR в ветку main

jobs:
  build:
    runs-on: ubuntu-latest  # Используем последнюю версию Ubuntu

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Клонируем код из репозитория

    - name: Log in to Docker Hub
      uses: docker/login-action@v2  # Логинимся в Docker Hub
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Ваш Docker логин
        password: ${{ secrets.DOCKER_PASSWORD }}  # Ваш Docker токен

    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .  # Собираем Docker образ

    - name: Push Docker Image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest  # Отправляем Docker образ на Docker Hub

